### PR TITLE
Upgrade to Spring 3

### PR DESCRIPTION
**Pull request by mslowiak**
Closes: #43

### CODE REVIEW

**Comment by mslowiak** [comment]
@josdem working on my side but please test it on your side as well because it is big change

**Comment by mslowiak** [comment]
I found out problems with tests, changing to draft

**Comment by josdem** [comment]
Hi @mslowiak, thanks for creating a PR to update to spring `3.0.5` this is the error I am seeing when running tests or trying to start the application:
```bash
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServletRequest
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
```
Not sure why this is happening. I will investigate this in detail

**Comment by mslowiak** [comment]
I think that the springfox is the problem here - it is not yet compatible with Spring 3.
https://github.com/springfox/springfox/issues/3983 

If we want to move to the Spring 3, then we should migrate springfox to springdoc, see [migration guide](https://springdoc.org/v2/#migrating-from-springfox)

**Comment by josdem** [comment]
I agree; springfox is the issue here. We want to migrate to Spring Doc as the next step. I went ahead and create a new issue in the repository, please take a look at it [here](https://github.com/josdem/jmailer-spring-boot/issues/45)

**Pull request closed without merging**
